name: Test for pull request

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm run test
