name: Test for pull request

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Checkout master
        uses: actions/checkout@master
      - name: Run test
        run: yarn test
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build
        run: yarn build
