name: Notification process

on:
  schedule:
    - cron: '1 16 * * 5'

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    env:
      GH_API_KEY: ${{ secrets.GH_API_KEY }}
      HOOK_URL: ${{ secrets.HOOK_URL }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build
        run: yarn build
      - name: Slack notify
        run: yarn run start:notify
