name: Update daily data

on:
  schedule:
    - cron: '* 1 * * 1-6'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Checkout master
        uses: actions/checkout@master
      - name: Run test
        run: yarn test
  run:
    name: Update firestore
    runs-on: ubuntu-latest
    env:
      GH_API_KEY: ${{ secrets.GH_API_KEY }}
      FIRESTORE_SA_KEY: ${{ secrets.FIRESTORE_SA_KEY }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build
        run: yarn build
      - name: Update data
        run: yarn run start
